version: "3.7"
services:
  nginx_app:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - flask_app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '${portNginx}'
    

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '5000'
    environment:
      - PASSWORD=${PASSWORD}
      - Host=${Host}
      - Port=${Port}
    depends_on:
      - redis
   

  redis:
    image: redis:latest
    command: redis-server --requirepass ${PASSWORD} --appendonly yes    
    volumes:
      - ./redis-vol:/data 
    expose:
      - '6379'
  nginx_static:
    build:
      context: ./static
      dockerfile: Dockerfile
    ports:
      - ${staticnginx}
    volumes:
      - ./data:/srv
